#!/bin/bash
# ============================================================
# TRACE — Fresh environment setup script
# Run this at the start of every new session or on EC2 boot
# Does two things:
#   1. Pulls secrets from AWS Parameter Store → writes .env
#   2. Downloads VideoSeal model if not already present
# ============================================================

set -e

echo "🔧 Setting up TRACE environment..."

# ── Step 1: Pull secrets from AWS Parameter Store ──────────
echo "🔑 Fetching secrets from AWS Parameter Store..."

fetch() {
  aws ssm get-parameter --name "/trace/$1" --with-decryption --query "Parameter.Value" --output text
}

{
  echo "# Auto-generated by setup.sh — do not edit manually"
  echo "AWS_ACCESS_KEY_ID=$(fetch AWS_ACCESS_KEY_ID)"
  echo "AWS_SECRET_ACCESS_KEY=$(fetch AWS_SECRET_ACCESS_KEY)"
  echo "AWS_REGION=$(fetch AWS_REGION)"
  echo "S3_UPLOAD_BUCKET=$(fetch S3_UPLOAD_BUCKET)"
  echo "S3_OUTPUT_BUCKET=$(fetch S3_OUTPUT_BUCKET)"
  echo "DATABASE_URL=$(fetch DATABASE_URL)"
  echo "RESEND_API_KEY=$(fetch RESEND_API_KEY)"
} > .env

echo "✅ .env written successfully"

# ── Step 2: Download VideoSeal model if missing ────────────
MODEL_DIR="backend/ckpts"
MODEL_FILE="$MODEL_DIR/y_256b_img.jit"

if [ -f "$MODEL_FILE" ]; then
  echo "✅ VideoSeal model already exists — skipping download"
else
  echo "📥 Downloading VideoSeal model (218MB)..."
  mkdir -p "$MODEL_DIR"
  wget -q --show-progress \
    https://dl.fbaipublicfiles.com/videoseal/y_256b_img.jit \
    -O "$MODEL_FILE"
  echo "✅ VideoSeal model downloaded to $MODEL_FILE"
fi

echo ""
echo "🚀 TRACE environment ready. Start the backend with:"
echo "   cd backend && uvicorn main:app --reload --port 8000"
